# Generated by Django 5.2 on 2025-05-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_kursy_valyut_tag_weather_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
