# Generated by Django 5.2 on 2025-05-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
