# Generated by Django 5.2 on 2025-05-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
